[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ssp-course-track3-baseline"
version = "1.0.0"
description = "Spatial-semantic sound-scene segmentation baseline for SSP course Track 3"
readme = "README.md"
dependencies = [
  "einops",
  "huggingface-hub",
  "librosa",
  "lightning",
  "netCDF4",
  "nnAudio",
  "numpy",
  "pysofaconventions",
  "python-sofa",
  "pytorch-lightning",
  "pytz",
  "PyYAML",
  "scipy",
  "soundfile",
  "tensorboard",
  "timm",
  "torchlibrosa",
  "torchmetrics",
  "tqdm",
  "transformers",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
namespaces = true
